### PR TITLE
Reformated to be a proper package

### PR DESCRIPTION
**Pull request by rodrigob**
Here is my pull request to address issue #9.
I squashed all my mini-changes into a big commit (other repositories like to do that).

I tried a fresh install into a virtualenv and it seemed to work fine. So unless I messed-up with my git manipulations, this should solve the issue.

Note that setup.py will also install pydensecrf.util as required.

I created my own playground applications to use it. Maybe `util_inference_example.py` should be moved of the package, and have it call `import pydensecrf.densecrf` and `import pydensecrf.utils`; so as to show the proper use of the library.

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
Thanks a lot, just tested and it seems to work for me too! Good call on squashing, I prefer that too.

Few minor comments:

- The history of `SparseAssign.h` is weird, if it's easy to fix and squash+force-push that, I'd be grateful; but nevermind if it's a hassle.
- `*~` and `.idea` don't belong into a project's `.gitignore` but rather into your [global `.gitignore`](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore), so would you mind taking them out, squashing and force-pushing?
- I agree with your comment on `util_inference_example.py`. Could you do that? (and `import pydensecrf.densecrf as dcrf` so we set a nice example.) I don't mind whether you squash this one or keep this commit separate.

**Comment by lucasb-eyer** [comment]
Oh, and if you write something like "Fixes #9" into the commit message, github will automatically close that issue when merging this PR.

**Comment by rodrigob** [comment]
Just updated my branch with these changes. I had problems with github and squashed commits (I am not a git guru, more of a hg guy), so I ended having "repeated commits". 
I hope you can fix the commits history on your side.

**Comment by rodrigob** [comment]
Just noticed a minor change lost in my git fights. Pushed back as one extra commit.

**Comment by lucasb-eyer** [comment]
Merged manually with clean history, See c0550af, 19119d31a5, and 1463feb. If you want to [take credit](https://github.com/lucasb-eyer/pydensecrf/graphs/contributors), I recommend you associate the e-mail address that you committed with (`@mpi...`) with your github account!

**Comment by lucasb-eyer** [comment]
Also, closing manually since it looks like github doesn't auto-detect manual merges.

**Comment by lucasb-eyer** [comment]
Thanks a lot for sharing this with us!

**Pull request closed without merging**
